image: composer/composer:latest
pipelines:
  default:
    - step:
        script:
          # Show software versions.
          - composer self-update
          - composer --version
          - php -v

          # Install SSH keys.
          - mkdir -p /root/.ssh
          - chmod 700 /root/.ssh

          - echo "$PIPELINES_PRIVATE_KEY" | sed 's/\\n/\n/g' | cat > /root/.ssh/id_rsa
          - chmod 600 /root/.ssh/id_rsa

          - echo "$BITBUCKET_KNOWN_HOSTS" >> /root/.ssh/known_hosts

          # Composer installation.
          - echo "$COMPOSER_AUTHENTICATION" > $COMPOSER_HOME/auth.json
          - composer validate --strict --no-interaction
          - export BIN=$(composer config bin-dir)

          - composer require mediact/testing-suite --dev --prefer-dist --no-scripts --ignore-platform-reqs --no-progress --optimize-autoloader --no-interaction

          # Require the coding standards, if they are not explicitly defined.
          # Execute tests from MediaCT testing bundle
          - $BIN/mediact-testing-suite