image: srcoder/development-php:php74-fpm
definitions:
  caches:
    vendor: vendor
pipelines:
  default:
    - step:
        name: Testing suite
        caches:
          - composer
          - vendor
        script:
          - composer self-update --1
          - if [ -f "composer.lock" ]; then composer check-platform-reqs; fi
          - if [ -n "$COMPOSER_PRE_INSTALL_CALLBACK" ]; then eval $COMPOSER_PRE_INSTALL_CALLBACK; fi
          - composer install --dev --prefer-dist --no-scripts --no-progress --optimize-autoloader --no-interaction -vvv
          - composer show
          - composer exec -v grumphp run
